### ISSUE TITLE
Improve the icon

### ISSUE THREAD

**Issue by aaronfranke** [JulienVanelian/godot-folder-node#1]
The icon for this add-on is white text on a transparent background, which means that this icon is invisible in the Asset Library as it's white text on a white background. A simple way to fix this would be to make the background a solid black color, but there are also other ways to fix this, such as changing the text color, or making the icon symbolic (ex: so that it looks like a physical folder).

**Comment by JulienVanelian** [comment]
Thanks! I changed the icon for a folder-like icon, with a border
